/**
 * Ver  Ticket#      Date            Author                 Purpose
 * 1.0  JN1-4045     25/11/2020      Ishwari G.(thinqloud)  Added constants to refere values from custom metadata
 **/
public class Constants {
  public static final String NONE = 'None';
  public static final String DEFAULT_METADATA_LABEL = 'Default';
  public static final String INVALID_TENURE = 'Sorry an invalid tenure has been entered. Please be reminded a tenure has to be greater than 0 and less than 10.';
  public static final Integer MAX_CREDITOR_LIFE_AGE = 64;

  //JN1-4045
  public static final String AGE = 'Age';
  public static final String EDUCATION = 'Highest Level of Education attained';
  public static final String STATUS_OF_ADDRESS = 'Status of Address';
  public static final String YEARS_AT_RESIDENCE = 'Years at Residence';
  public static final String CREDIT_HISTORY = 'Credit History over the last 24 months';
  public static final String NET_WORTH = 'Assessment of Applicant Net Worth';
  public static final String EMPLOYMENT_STATUS = 'Employment Status';
  public static final String INDUSTRY = 'Industry';
  public static final String LENGTH_OF_EMPLOYMENT = 'Length of Employment';
  public static final String PROFESSIONAL_CATEGORY = 'Professional Category';
  public static final String WORKING_CAPITA = 'Working Capital';
  public static final String NATURE_OF_ENGAGEMENT = 'Nature of Engagement';
  public static final String FINANCIAL_PERFORMANCE = 'Assessment of Business Fin Performance';
  public static final String FINACIAL_STATEMENT = 'Assessment of Business Fin Statement';
  public static final String LENGTH_OF_TRADE = 'Length of trade';
  public static final String COLLATERAL = 'Collateral CC / Collateral LOC';
  public static final String LOAN_TO_VALUE = 'Loan to Value CC / Loan to Value LOC';
  public static final String ABILITY_TO_SERVICE = 'Ability to Service CC / Ability to Service LOC';
  public static final String REPAYMENT_METHOD = 'Repayment Method CC / Repayment Method LOC';

  public static final String LESS_THAN_YEAR = 'Less than a 1 year';
  public static final String BETWEEN_1_3_YEARS = 'Between 1-3 years';
  public static final String BETWEEN_3_5_YEARS = 'Between 3-5 years';
  public static final String LT_1_YEAR = '<1 year';
  public static final String ONE_TO_THREE_YEARS = '1-3 years';
  public static final String THREE_TO_FIVE_YEARS = '3-5 years';
  public static final String GT_5_YEARS = '>5 years';
  public static final String EMPLOYED = 'Employed';
  public static final String YEARS = 'years';
  public static final String YEAR = 'year';
  public static final String OWN = 'Own';
  public static final String POST_GRADUATE = 'Post Graduate';
  public static final String UNDERGRADUATE_GRADUATE = 'Undergraduate';
  public static final String VOCATIONAL = 'Vocational';
}
