public class Constants {
  public static final String NONE = 'None';
  public static final String DEFAULT_METADATA_LABEL = 'Default';
  public static final String INVALID_TENURE = 'Sorry an invalid tenure has been entered. Please be reminded a tenure has to be greater than 0 and less than 10.';
  public static final Integer MAX_CREDITOR_LIFE_AGE = 64;
  public static final String APPLICANT_WRAPPER = 'Applicant Wrapper';
  public static final String APPLICANT_ASSETS_AND_LIABILITIES_WRAPPER = 'Assets and Liabiltiy Wrapper';
}
