/**
 * @description       :
 * @author            : Remario Richards
 * @group             :
 * @last modified on  : 05-26-2021
 * @last modified by  : Remario Richards
 * Modifications Log
 * Ver   Date         Author             Modification
 * 1.0   05-26-2021   Remario Richards   Initial Version
 **/
public with sharing class OneJNQuerySelector {
  /**
   * @description retrieve accounts
   * @author Remario Richards | 05-26-2021
   **/
  public static void getAccounts() {
  }
  /**
   * @description get applicants
   * @author Remario Richards | 05-26-2021
   **/
  public static void getApplicants() {
  }
  /**
   * @description get  applications
   * @author Remario Richards | 05-26-2021
   **/
  public static void getApplications() {
  }

  /**
   * @description get  loan calculations
   * @author Remario Richards | 05-26-2021
   **/
  public static void getLoanCalculations() {
  }
  /**
   * @description get  loan calculation products
   * @author Remario Richards | 05-26-2021
   **/
  public static void getLoanCalculationProducts() {
  }
}
