public class ProductDetailsSerializer {
  @AuraEnabled
  public Integer years;
  @AuraEnabled
  public Integer months;
  @AuraEnabled
  public Decimal market;
  @AuraEnabled
  public Decimal loanAmount;
  @AuraEnabled
  public Decimal minimumOfPurchaseMarketValue;
  @AuraEnabled
  public Decimal marketValue;
  @AuraEnabled
  public Decimal purchasePrice;
  @AuraEnabled
  public String interestedInPremiumFlag;
  @AuraEnabled
  public String jngiIncludeInLoan;
  @AuraEnabled
  public Decimal jngiMonthlyPremium;
  @AuraEnabled
  public String interestedInCreditorLife;
  @AuraEnabled
  public String coverageType;
  @AuraEnabled
  public String includeInLoanAmountCreditorLife;
  @AuraEnabled
  public String waiveProcessingFeeFlag;
  @AuraEnabled
  public String includeInLoanAmountFlag;
  @AuraEnabled
  public Decimal processingFeePercentagePerAnum;
  @AuraEnabled
  public String repaymentMethod;
  @AuraEnabled
  public String monthlyRepaymentDate;
  @AuraEnabled
  public Decimal proposedSavingPercentage;
  @AuraEnabled
  public Decimal proposedSavingAmount;
  @AuraEnabled
  public Decimal TDSRBefore;
  @AuraEnabled
  public Decimal TDSRAfter;
  @AuraEnabled
  public Decimal LTVValue;
  @AuraEnabled
  public Decimal existingDebt;
  @AuraEnabled
  public Decimal supplementaryApplicantAnnualMembership;
  @AuraEnabled
  public Decimal existingDebtAfter;
  @AuraEnabled
  public Decimal monthlyPrincipalInterestProcessingFee;
  @AuraEnabled
  public Decimal processingFeesGCT;
  @AuraEnabled
  public Decimal processingFeeClosingCost;
  @AuraEnabled
  public Decimal monthly_PI_LoanAmount;
  @AuraEnabled
  public Decimal startingLimit;
  @AuraEnabled
  public String cardType;
  @AuraEnabled
  public Decimal policyLimit;
  @AuraEnabled
  public Decimal totalClosingCost;
  @AuraEnabled
  public Decimal nsipp;
  @AuraEnabled
  public Decimal stampDuty;
  @AuraEnabled
  public Decimal legalFee;
  @AuraEnabled
  public Decimal assignmentFee;
  @AuraEnabled
  public Decimal totalLoanAmount;
  @AuraEnabled
  public Decimal totalMonthlyLoanPayment;
  @AuraEnabled
  public Decimal monthlyCompulsorySavings;
  @AuraEnabled
  public String repaymentDate;
  @AuraEnabled
  public Decimal proposedSavingsPercentage;
  @AuraEnabled
  public Decimal proposedSavingsAmount;
  @AuraEnabled
  public String collateralType;

  @AuraEnabled
  public Decimal jngiMotorPremium;
  @AuraEnabled
  public Decimal monthlyPIJNGIMotorPremium;
  @AuraEnabled
  public Decimal jnLifeCreditorPremium;
  @AuraEnabled
  public Decimal totalCompulsorySavingsBalance;
  @AuraEnabled
  public Decimal monthlyJnLifeCreditor_PI_Premium;
  @AuraEnabled
  public Decimal totalMonthly_PI_LoanPayment;
  @AuraEnabled
  public Decimal totalInterestPaymentBalance;

  @AuraEnabled
  public Decimal totalMonthlyLoanPaymentAndSavings;
  @AuraEnabled
  public Decimal jnCLPremiumFeesAndCharges;
  @AuraEnabled
  public Decimal stampDutyAndAdminCharges;
  @AuraEnabled
  public Decimal totalFinancedByJN;
  @AuraEnabled
  public Decimal totalClosingCostsApplicantPayable;
  @AuraEnabled
  public String noCreditorLifeReason;
  @AuraEnabled
  public String policyProvider;
  @AuraEnabled
  public Decimal primaryApplicantAnnualMembership;
  @AuraEnabled
  public Decimal numberOfSupplementaryCardHolders;
  @AuraEnabled
  public Decimal creditorLifeAnnualFee;
  @AuraEnabled
  public Decimal minimumPayment;
  @AuraEnabled
  public Decimal creditorLifePremiumForNonRevolvingLoan;
  @AuraEnabled
  public Decimal approvedStartingLimit;

  @AuraEnabled
  public String financialInstitution;
  @AuraEnabled
  public String accountType;
  @AuraEnabled
  public String depositAccountNumber;
  @AuraEnabled
  public String accountHolder;
  @AuraEnabled
  public String hypothecatedLoan;
  @AuraEnabled
  public Decimal depositBalance;
  @AuraEnabled
  public Decimal annualInterestRate;
  @AuraEnabled
  public Decimal existingBalance;
}
